### ISSUE TITLE
Failed to activate the js-refactor package

### ISSUE THREAD

**Issue by jameswlane** [hax/js-refactor#17]
[Enter steps to reproduce below:]
1. Launch Atom

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [js-refactor](https://github.com/hax/js-refactor) package, v0.7.3
### Stack Trace

Failed to activate the js-refactor package

```
At Cannot find module 'babel-runtime/core-js/get-iterator'

Error: Cannot find module 'babel-runtime/core-js/get-iterator'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/node_modules/babylon/lib/parser/index.js:8:21)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/node_modules/babylon/lib/index.js:9:15)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/Context.js:11:16)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/ripper.coffee:1:11)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/ripper.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/js_refactor.js:18:15)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "hyperclick",
      "nuclide-arcanist",
      "nuclide-blame",
      "nuclide-blame-provider-hg",
      "nuclide-blame-ui",
      "nuclide-buck-files",
      "nuclide-clang-atom",
      "nuclide-code-format",
      "nuclide-debugger-atom",
      "nuclide-debugger-hhvm",
      "nuclide-debugger-lldb",
      "nuclide-diagnostics-store",
      "nuclide-diagnostics-ui",
      "nuclide-diff-view",
      "nuclide-file-tree",
      "nuclide-file-watcher",
      "nuclide-find-references",
      "nuclide-flow",
      "nuclide-format-js",
      "nuclide-fuzzy-filename-provider",
      "nuclide-hack",
      "nuclide-hack-symbol-provider",
      "nuclide-hg-repository",
      "nuclide-installer",
      "nuclide-language-hack",
      "nuclide-move-pane",
      "nuclide-objc",
      "nuclide-ocaml",
      "nuclide-open-filenames-provider",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-test-runner",
      "nuclide-toolbar",
      "nuclide-type-hint",
      "tree-view",
      "activate-power-mode"
    ],
    "projectHome": "/Workbench"
  }
}
```
### Installed Packages

``` coffee
# User
achievements, v0.9.0
achiever, v0.1.1
atom-ternjs, v0.14.2
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
autocomplete-modules, v1.5.2
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
change-case, v0.6.3
color-picker, v2.2.2
compare-files, v0.6.2
css-snippets, v0.9.0
ctags-status, v1.3.5
editorconfig, v1.4.1
file-icons, v1.7.17
fonts, v1.6.0
git-diff-details, v1.3.0
git-tab-status, v1.9.2
goto-definition, v1.1.18
grunt-runner, v0.14.0
gulp-snippets, v0.6.2
hashrocket, v0.4.10
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
js-refactor, v0.7.3
language-babel, vundefined
language-docker, v1.1.6
language-ini, v1.16.0
language-javascript-jsx, v0.3.7
language-ocaml, v1.1.2
language-thrift, v1.0.2
linter, v1.11.14
linter-eslint, v7.2.4
linter-ruby, v1.2.2
linter-scss-lint, v3.0.4
merge-conflicts, v1.4.4
minimap, v4.24.7
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.1
node-debugger, vundefined
nuclide, v0.158.0
open-recent, v5.0.0
pigments, v0.31.2
project-manager, v2.9.7
react, v0.15.0
react-snippets, v0.4.2
refactor, v0.9.2
save-session, v0.16.0
set-syntax, v0.3.0
tabs-to-spaces, v1.0.2
terminal-plus, v0.14.5
terminal-status, v1.6.8
test-status, v1.0.0
tidy-tabs, v0.3.0
time-status, v1.1.2
tool-bar, v1.0.0
trailing-spaces, v0.3.2
tree-view-git-projects, v0.5.0
tree-view-git-status, v1.0.2
underscorejs-snippets, v0.2.2
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by jameswlane** [comment]
[Enter steps to reproduce below:]
1. Start Atom

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [js-refactor](https://github.com/hax/js-refactor) package, v0.7.3

### Stack Trace

Failed to activate the js-refactor package

```
At Cannot find module 'babel-runtime/core-js/get-iterator'

Error: Cannot find module 'babel-runtime/core-js/get-iterator'
  at Module._resolveFilename (module.js:339:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/node_modules/babylon/lib/parser/index.js:8:21)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/node_modules/babylon/lib/index.js:9:15)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/Context.js:11:16)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/ripper.coffee:1:11)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/ripper.coffee:1:1)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/jl82576/.atom/packages/js-refactor/lib/js_refactor.js:18:15)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:718:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:765:28

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "hyperclick",
      "nuclide-arcanist",
      "nuclide-blame",
      "nuclide-blame-provider-hg",
      "nuclide-blame-ui",
      "nuclide-buck-files",
      "nuclide-clang-atom",
      "nuclide-code-format",
      "nuclide-debugger-atom",
      "nuclide-debugger-hhvm",
      "nuclide-debugger-lldb",
      "nuclide-diagnostics-store",
      "nuclide-diagnostics-ui",
      "nuclide-diff-view",
      "nuclide-file-tree",
      "nuclide-file-watcher",
      "nuclide-find-references",
      "nuclide-flow",
      "nuclide-format-js",
      "nuclide-fuzzy-filename-provider",
      "nuclide-hack",
      "nuclide-hack-symbol-provider",
      "nuclide-hg-repository",
      "nuclide-installer",
      "nuclide-language-hack",
      "nuclide-move-pane",
      "nuclide-objc",
      "nuclide-ocaml",
      "nuclide-open-filenames-provider",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-test-runner",
      "nuclide-toolbar",
      "nuclide-type-hint",
      "tree-view",
      "activate-power-mode"
    ],
    "projectHome": "/Workbench"
  }
}
```

### Installed Packages

``` coffee
# User
achieve-atom, v0.7.0 (inactive)
achievements, v0.9.0 (inactive)
achiever, v0.1.1 (inactive)
advanced-new-file, v0.5.0 (inactive)
atom-beautify, v0.29.11 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-lcov, v2.0.0 (inactive)
atom-monokai, v0.10.4 (inactive)
atom-ternjs, v0.15.0 (inactive)
auto-detect-indentation, v1.2.0 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-modules, v1.6.1 (inactive)
autocomplete-paths, v1.0.2 (inactive)
autocomplete-sass, v0.1.0 (inactive)
change-case, v0.6.3 (inactive)
clipboard-history, v0.6.6 (inactive)
color-picker, v2.2.2 (inactive)
compare-files, v0.8.0 (inactive)
css-snippets, v1.0.0 (inactive)
ctags-status, v1.3.5 (inactive)
duotone-dark-syntax, v1.0.0 (inactive)
duplicate-line-or-selection, v0.5.0 (inactive)
editorconfig, v1.4.1 (inactive)
file-icons, v1.7.19 (inactive)
file-templates, v0.2.0 (inactive)
fonts, v1.6.0 (inactive)
gist-it, v0.9.1 (inactive)
git-control, v0.8.2 (inactive)
git-diff-details, v1.3.0 (inactive)
git-plus, v5.16.2 (inactive)
git-projects, v1.17.0 (inactive)
git-tab-status, v1.9.2 (inactive)
git-time-machine, v1.5.3 (inactive)
goto-definition, v1.1.19 (inactive)
hashrocket, v0.4.10 (inactive)
haskell-grammar, v0.4.0 (inactive)
highlight-selected, v0.11.2 (inactive)
javascript-snippets, v1.2.1 (inactive)
jquery-snippets, v11.0.0 (inactive)
js-refactor, v0.7.3 (inactive)
language-babel, vundefined (inactive)
language-docker, v1.1.7 (inactive)
language-ini, v1.16.0 (inactive)
language-javascript-jsx, v0.3.7 (inactive)
language-ocaml, v1.1.2 (inactive)
language-swift, v0.4.0 (inactive)
language-thrift, v1.0.2 (inactive)
linter, v1.11.16 (inactive)
linter-eslint, v7.2.4 (inactive)
linter-ruby, v1.2.2 (inactive)
linter-scss-lint, v3.0.4 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-git-diff, v4.3.1 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-pigments, v0.2.1 (inactive)
mocha-test-runner, v0.5.1 (inactive)
mocha-ui, v0.1.8 (inactive)
monokai-seti, v0.7.0 (inactive)
node-debugger, vundefined (inactive)
nucleus-dark-ui, v0.9.5 (inactive)
nuclide, v0.166.0 (inactive)
open-recent, v5.0.0 (inactive)
pigments, v0.34.0 (inactive)
pomodoro, v1.0.1 (inactive)
project-manager, v2.9.7 (inactive)
react, v0.16.0 (inactive)
react-snippets, v0.4.2 (inactive)
refactor, v0.9.2 (inactive)
save-session, v0.16.0 (inactive)
set-syntax, v0.3.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
tabs-to-spaces, v1.0.2 (inactive)
terminal-plus, v0.14.5 (inactive)
terminal-status, v1.6.8 (inactive)
test-status, v1.0.0 (inactive)
tidy-tabs, v0.3.0 (inactive)
time-status, v1.1.2 (inactive)
todo-show, v1.7.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tool-bar, v1.0.1 (inactive)
trailing-spaces, v0.3.2 (inactive)
tree-view-git-projects, v0.5.0 (inactive)
tree-view-git-status, v1.1.0 (inactive)
turbo-javascript, v1.4.0 (inactive)
underscorejs-snippets, v0.2.2 (inactive)
webbox-color, v0.5.9 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by hax** [comment]
Close old issues which not reproducible. Feel free to reopen it if it occur again.
