### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mistadikay** [hax/js-refactor#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.11
**Thrown From**: [js-refactor](https://github.com/hax/js-refactor) package, v0.6.0
### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/lazhcm10348/.atom/packages/js-refactor/vender/esrefactor.js:76

TypeError: Cannot read property 'name' of undefined
  at _locateDeclaration (/Users/lazhcm10348/.atom/packages/js-refactor/vender/esrefactor.js:76:67)
  at Context._lookupDeclaration (/Users/lazhcm10348/.atom/packages/js-refactor/vender/esrefactor.js:147:22)
  at Context.identify (/Users/lazhcm10348/.atom/packages/js-refactor/vender/esrefactor.js:270:32)
  at Ripper.module.exports.Ripper.find (/Users/lazhcm10348/.atom/packages/js-refactor/lib/ripper.coffee:76:31)
  at Watcher.module.exports.Watcher.createReferences (/Users/lazhcm10348/.atom/packages/refactor/lib/watcher.coffee:137:22)
  at Watcher.module.exports.Watcher.onCursorMovedAfter (/Users/lazhcm10348/.atom/packages/refactor/lib/watcher.coffee:249:6)
  at /Users/lazhcm10348/.atom/packages/refactor/lib/watcher.coffee:1:1

```
### Commands

```
     -2:09.1.0 core:cut (atom-text-editor.editor.is-focused)
     -2:08.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -2:08.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:06.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:06.6.0 refactor:done (atom-text-editor.editor.is-focused)
     -2:06.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:06.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:05.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:08.9.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  4x -1:06.7.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -0:53.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:48.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.9.0 core:close (button.btn.icon.enablement.icon-playback-play)
     -0:04.1.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:03.8.0 core:select-right (atom-text-editor.editor.is-focused)
  2x -0:03.2.0 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "metrics",
      "language-toml",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-csharp",
      "language-c",
      "background-tips",
      "archive-view",
      "project-palette-finder",
      "linter-csslint",
      "linter-less",
      "linter-scss-lint",
      "linter-jscs",
      "autocomplete-glsl",
      "github-issues",
      "language-javascript",
      "language-clojure",
      "language-objective-c",
      "language-go",
      "language-javascript-jsx",
      "open-last-project",
      "javascript-refactoring",
      "bookmark-panel",
      "minimap-bookmarks",
      "minimap-find-and-replace",
      "minimap-autohide",
      "autohide-tree-view",
      "autocomplete-atom-api",
      "node-resolver",
      "tool-bar-main",
      "mechanical-keyboard",
      "git-control",
      "language-javascript-better",
      "language-api-blueprint",
      "nuclide-hack",
      "nuclide-flow",
      "nuclide-file-tree",
      "nuclide-hg-repository",
      "nuclide-language-hack",
      "nuclide-remote-projects",
      "nuclide-diff-view",
      "nuclide-click-to-symbol",
      "nuclide-code-format",
      "nuclide-file-watcher",
      "nuclide-installer",
      "nuclide-quick-open",
      "nuclide-type-hint",
      "travis-ci-status",
      "js-refactor"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.12
atom-pair, v2.0.10
atom-wallaby, v1.0.4
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
color-picker, v2.0.11
custom-title, v1.0.1
editorconfig, v1.2.0
emmet, v2.3.12
file-icons, v1.6.9
flex-tool-bar, v0.5.0
fonts, v0.6.0
highlight-selected, v0.10.1
language-babel, v0.13.6
language-gitignore, v0.2.0
linter, v1.5.1
linter-eslint, v3.0.2
minimap, v4.13.3
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
node-debugger, v1.1.8
package-sync, v0.2.0
pigments, v0.14.0
project-manager, v2.5.1
react, v0.12.8
refactor, v0.6.0
regex-railroad-diagram, v0.8.4
remote-edit, v1.8.18
svg-preview, v0.6.1
tool-bar, v0.1.9
wakatime, v4.0.16

# Dev
No dev packages
```

**Comment by ianzepp** [comment]
For me, this is instantly reproducable by simply using the keyword "arguments". Any click near to the keyword will then reliably throw this exception. For example, when doing something like this:

```
    return {
        get: function() {
            var ns = '...';
            var endpoint = _.flatten([base, ns, arguments], true).join('/');
            ...
```

"arguments" as used here is simply to be able to quickly collect any function arguments without have to explicitly enumerate them.

**Comment by cfv1984** [comment]
Same as @ianzepp . I just type the word "arguments" and instantly get an error.

**Comment by JerrySievert** [comment]
+1

**Comment by capaj** [comment]
same as @ianzepp

**Comment by jonathansamines** [comment]
+1

**Comment by ronkorving** [comment]
Yeah, same here... sorry for the noise, but .. +1

**Comment by kamyarinfinity** [comment]
Same here. 'arguments' is the source of the problem.

**Comment by trevorhreed** [comment]
Looks like it may be a problem with the vendor code: https://github.com/ariya/esrefactor. I've opened an issue on that project.

**Comment by RohovDmytro** [comment]
same + 1

**Comment by hax** [comment]
after 0.7.0 totally rewrite, it should never happen again.

**Comment by trevorhreed** [comment]
Are you still using esrefactor? Or are you replacing that library in 0.7.0?

**Comment by hax** [comment]
@trevorhreed Yes, I replaced esrefactor by babel-traverse in 0.7 . Now we can enable all syntax babel support, such as JSX :)
